name: Core Test & Binary Build
on:
  push:
    branches: [ master, eugene/* ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Init submodules
      run: ./git-init-submodules.sh
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/build.gradle') }}
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
    - name: Setup gradle binaries
      run: ./gradlew
    - name: Pull dependencies libs, and perform initial compile
      run: ./gradlew src
    - name: Run unit tests
      run: ./gradlew test
    - name: Run the build
      run: ./gradlew build
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: |
          build/reports/**/*
          build/test-results/**/*
          build/jacoco/**/*
    - name: Archive binary files
      uses: actions/upload-artifact@v2
      with:
        name: binary-libs
        path: |
          build/libs/**/*
