name: Local Sqlite Support Test
on:
  push:
    branches: [ master, "*" ]
  pull_request:
    branches: [ master ]
jobs:
  unit_test:
    runs-on: ubuntu-latest

    # Because github services, does not allow overwriting "CMD" / "ENTRYPOINT" commands
    # so we are gonna to run the docker containers via the bash commandline
    # services:
    #   postgres:
    #     image: cockroachdb/cockroach:v21.1.12
    #     env:
    #       POSTGRES_DATABASE: javacommons
    #       POSTGRES_USER: javacommons
    #       POSTGRES_PASSWORD: javacommons
    #     ports:
    #       - 26257:26257
    #     options: --health-cmd="curl http://localhost:8080/health?ready=1" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v1
    - name: Init submodules
      run: ./git-init-submodules.sh
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/build.gradle') }}
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
    - name: Setup gradle binaries
      run: ./gradlew
    - name: Pull dependencies libs, and perform initial compile
      run: ./gradlew src
    - name: Run unit tests
      run: ./gradlew test -Ptest_sqlite
    - name: Run jacocoTestReport
      run: ./gradlew jacocoTestReport
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-result-report
        path: |
          build/reports/**/*
          build/test-results/**/*
          build/jacoco/**/*
    - name: Upload code coverage to codecov
      uses: codecov/codecov-action@v2
      if: always()
      with:
        # flags: gradle-build # optional
        # directory: build/jacoco/
        verbose: true # optional (default = false)
        fail_ci_if_error: false
