name: MySql 5.7 Support Test
on:
  push:
    branches: [ master, eugene/* ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: JAVACOMMONS
          MYSQL_USER: JAVACOMMONS
          MYSQL_PASSWORD: JAVACOMMONS
          MYSQL_ROOT_PASSWORD: ROOTPASSWD
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v1
    - name: Init submodules
      run: ./git-init-submodules.sh
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/build.gradle') }}
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
    - name: Setup gradle binaries
      run: ./gradlew
    - name: Pull dependencies libs, and perform initial compile
      run: ./gradlew src
    - name: Run unit tests
      run: ./gradlew test -Ptest_mysql
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: code-coverage-report
        path: |
          build/reports/**/*
          build/test-results/**/*
          build/jacoco/**/*
