name: (perf) Postgres 14.1 Support Test
on:
  push:
    branches: [ master, eugene/* ]
  pull_request:
    branches: [ master ]
jobs:
  perf_test:
    runs-on: ubuntu-latest
    
    # Because github services, does not allow overwriting "CMD" / "ENTRYPOINT" commands
    # so we are gonna to run the docker containers via the bash commandline
    # services:
    #   postgres:
    #     image: postgres:14.1
    #     env:
    #       POSTGRES_DATABASE: javacommons
    #       POSTGRES_USER: javacommons
    #       POSTGRES_PASSWORD: javacommons
    #     ports:
    #       - 26257:5432
    #     options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v1
    - name: Init submodules
      run: ./git-init-submodules.sh
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/build.gradle') }}
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
    - name: Setup cockroachDB 
      run: |
        sudo docker run -d \
          -e POSTGRES_DATABASE=javacommons \
          -e POSTGRES_USER=javacommons \
          -e POSTGRES_PASSWORD=javacommons \
          --name=postgres --hostname=postgres \
          -p 26257:5432 \
          postgres:14.1 \
          postgres -c 'max_connections=500'
        sleep 5s
    # - name: Setup initial postgres DB
    #   run: |
    #     sudo docker exec postgres cockroach sql --insecure -e "CREATE DATABASE IF NOT EXISTS javacommons" && \
    #     sudo docker exec postgres cockroach sql --insecure -e "CREATE USER IF NOT EXISTS javacommons" && \
    #     sudo docker exec postgres cockroach sql --insecure -e "GRANT ALL ON DATABASE javacommons TO javacommons"
    - name: Setup gradle binaries
      run: ./gradlew
    - name: Pull dependencies libs, and perform initial compile
      run: ./gradlew src
      # Running the various perf tests
    - name: Run perf unit tests
      run: |
        ./gradle-test-classpath.sh picoded.dstack.jsql.postgres.JSql_DataObjectMap_Postgres_perf
    - name: Run jacocoTestReport
      run: ./gradlew jacocoTestReport
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-result-report
        path: |
          build/reports/**/*
          build/test-results/**/*
          build/jacoco/**/*
    - name: Upload code coverage to codecov
      uses: codecov/codecov-action@v2
      if: always()
      with:
        # flags: gradle-build # optional
        # directory: build/jacoco/
        verbose: true # optional (default = false)
        fail_ci_if_error: false