name: Postgres 13.5 Support Test
on:
  push:
    branches: [ master, eugene/* ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13.5
        env:
          POSTGRES_DATABASE: javacommons
          POSTGRES_USER: javacommons
          POSTGRES_PASSWORD: javacommons
        ports:
          - 26257:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v1
    - name: Init submodules
      run: ./git-init-submodules.sh
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/build.gradle') }}
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
    - name: Setup gradle binaries
      run: ./gradlew
    - name: Pull dependencies libs, and perform initial compile
      run: ./gradlew src
    - name: Run unit tests
      run: ./gradlew test -Ptest_postgres
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: |
          build/reports/**/*
          build/test-results/**/*
          build/jacoco/**/*
